apiVersion: v1
kind: Pod
metadata:
  name: volume-share-xfusion
spec:
  volumes:
  - name: volume-share
    emptyDir: {}

  containers:
  - name: volume-container-xfusion-1
    image: centos:latest
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/news
    command: ["/bin/sh"]
    args: ["-c", "sleep 10000"]
  - name: volume-container-xfusion-2
    image: centos:latest
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/demo
    command: ["/bin/sh"]
    args: ["-c", "sleep 10000"]